# Generated by Django 3.0.3 on 2020-08-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_auto_20200814_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
