# Generated by Django 3.0.3 on 2020-08-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0009_auto_20200819_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
