# Generated by Django 3.0.3 on 2020-08-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0013_auto_20200819_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
