# Generated by Django 3.0.3 on 2020-08-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0015_auto_20200819_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
