# Generated by Django 3.0.3 on 2020-08-21 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0016_auto_20200820_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.')]),
        ),
    ]
